# Lab Task 01

Write a function to return True if the first and last number of a given list is same. If numbers are different then return False.

In [4]:
def same_numbers(a):
    l = len(a)
    if (a[0] == a[l-1]):
        return True
    else:
        return False

# Given:
numbers_x = [10, 20, 30, 40, 10]
numbers_y = [75, 65, 35, 75, 30]

print(same_numbers(numbers_x))
print(same_numbers(numbers_y))


True
False






# Lab Task 02

Create two NumPy arrays of the same shape and perform element-wise addition on them.

Calculate the element-wise product of two NumPy arrays.

In [14]:
#code here
import numpy as np
array1 = np.array([1,2,3,4,5])
array2 = np.array([1,2,3,4,5])
array3 = array1+array2
print("Element wise sum : ",array3)

array4 = array1*array2
print("Element wise product : ", array4)

Element wise sum :  [ 2  4  6  8 10]
Element wise product :  [ 1  4  9 16 25]


# Lab Task 03

# 

Reshape a 1D NumPy array into a 2D array with dimensions (3, 4).

Concatenate two NumPy arrays horizontally and vertically.

In [56]:
#code here
arr1 = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
arr2 = np.reshape(arr1, (3,4))

print(arr2)

arr3 = np.array([1,2,3,4,5])
arr4 = np.array([1,2,3,4,5])

print(np.concatenate((arr3,arr4),axis=None))

arr3v = np.vstack(arr3)
arr4v = np.vstack(arr4)
print(np.concatenate((arr3v, arr4v), axis=1))


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[1 2 3 4 5 1 2 3 4 5]
[[1 1]
 [2 2]
 [3 3]
 [4 4]
 [5 5]]


# Lab Task 04




## Online Store Shopping Cart
Write a Python program to simulate the online store's shopping cart system. The program should use a while loop to provide an interactive shopping experience.


### Tasks:
* Initialize an empty list called shopping_cart to store items.
* Display a welcome message and available products.
* Loop should be iterating over AI Response Simulator and Investment decision and keep asking for user input.
* Prompt the user to enter the number corresponding to the product they want to add to the cart.
* Check if the user entered 'q'. If so, break the loop.
* Convert the choice to an integer and validate it within the valid range (1 to 3).
* Based on the user's choice, add the selected product to the shopping_cart list.
* Display a confirmation message indicating the added product.
* Continue the loop to allow the user to add more products or proceed to checkout.
* After the loop ends, display the contents of the shopping cart.
* Display a goodbye message.
* End the program.


In [73]:
#Code here
shopping_cart = []
print("Welcome to the shopping cart".center(100))
products = {1:"Biscuits", 2:"Chips", 3:"Chocolate", 4:"Coke", 5:"Lollipop", 6:"Candy", 7:"Juice", 8:"Cupcakes", 9:"Noodles", 10:"Slanty"}
print("Available products are : \n",products)
print("\n\n")
while True:
    option = input("Enter the number corresponding to the product you want to add in the cart. \nPress 'q' to proceed to checkout\n")
    if option == 'q':
        break
    elif option.isdigit():
        opt = int(option)
        if opt< 1 or opt > 10:
            print("Product not available")
        else:
            shopping_cart.append(products[opt])
            print(products[opt], "successfully added to the shopping cart\n")
    else:
        print("Wrong option entered")
        
print("Your cart has following products : \n", shopping_cart)
print("\n\nGoodBye!!!!")


                                    Welcome to the shopping cart                                    
Available products are : 
 {1: 'Biscuits', 2: 'Chips', 3: 'Chocolate', 4: 'Coke', 5: 'Lollipop', 6: 'Candy', 7: 'Juice', 8: 'Cupcakes', 9: 'Noodles', 10: 'Slanty'}



Enter the number corresponding to the product you want to add in the cart. 
Press 'q' to proceed to checkout
23
Product not available
Enter the number corresponding to the product you want to add in the cart. 
Press 'q' to proceed to checkout
3
Chocolate successfully added to the shopping cart

Enter the number corresponding to the product you want to add in the cart. 
Press 'q' to proceed to checkout
7
Juice successfully added to the shopping cart

Enter the number corresponding to the product you want to add in the cart. 
Press 'q' to proceed to checkout
1
Biscuits successfully added to the shopping cart

Enter the number corresponding to the product you want to add in the cart. 
Press 'q' to proceed to checkout
8
Cupcak

# Lab Task 05


## Email Classification
Develope a tool which will classify an email.

### Tasks:
* Create a function classify_emails that takes a list of emails as an argument.
* Inside the function, categorize emails into "Important," "Promotions," and "Spam" based on keywords and content analysis.
* Loop through the emails and identify keywords to determine their category.
* If an email contains keywords indicating importance, assign it as "Important."
* If an email contains keywords related to promotions or deals, assign it as "Promotions."
* If an email is suspected to be spam based on certain keywords or patterns, assign it as "Spam."
* Return three lists of emails for each category.
* Print the lists.

In [76]:
#code here
from nltk import word_tokenize
def classify_emails(list1):
    important = []
    promotions = []
    spam = []
    imp_words = []
    for i in range(len(list1)):
        tokens = word_tokenize(list1[i])
        for t in tokens:
            if t == "Important" or t.lower() == "important":
                important.append(list1[i])
                break
            elif t == "Promotions" or t.lower() == "promotions":
                promotions.append(list1[i])
                break
            elif t == "Spam" or t.lower() == "spam":
                spam.append(list1[i])
                break
            else:
                continue
                
    return important,promotions,spam

emails = ["Important Emails", "Promotions Emails", "spam Emails"]
i,p,s = classify_emails(emails)

print("\nImportant Mails are : \n",i)
print("\nPromotion Mails are : \n",p)
print("\nSpam Mails are : \n",s)


Important Mails are : 
 ['Important Emails']

Promotion Mails are : 
 ['Promotions Emails']

Spam Mails are : 
 ['spam Emails']


# Lab Task 06

## English-Spanish Dictionary
You are creating a basic English-Spanish dictionary that allows users to look up English words and find their Spanish translations.


### Tasks
* Create a dictionary where English words are keys and their Spanish translations are values.
* Ask the user to input an English word.
* Check if the word exists in the dictionary.
* If the word exists, print its Spanish translation.
* If the word does not exist, inform the user that the translation is not available.
* Implement a loop that allows the user to keep looking up words until they choose to exit.


In [92]:
#code here
words_dict = {'hello': 'hola','goodbye': 'adiós','thank you': 'gracias','please': 'por favor','yes': 'sí','no': 'no','friend': 'amigo/amiga','family': 'familia','love': 'amor','peace': 'paz','water': 'agua','food': 'comida','house': 'casa','time': 'tiempo','work': 'trabajo','school': 'escuela','money': 'dinero','happy': 'feliz','sad': 'triste','beautiful': 'hermoso/hermosa'}
while True:
    word = input("Enter the english word : ")
    if word not in words_dict.keys():
        print("Translation not available!!")
    else:
        print(word, " \t", words_dict[word])
    ch = input("Do you want to look for more words : ('Y/y')")
    if ch == "Y" or ch == "y":
        continue
    else:
        break

Enter the english word : hello
hello  	 hola
Do you want to look for more words : ('Y/y')y
Enter the english word : what
Translation not available!!
Do you want to look for more words : ('Y/y')n


# Lab Task 07

dataset link : https://raw.githubusercontent.com/TirendazAcademy/PANDAS-TUTORIAL/main/DataSets/vgsalesGlobale.csv
#Exercise
Use the dataset of Game, we have explored earlier and perform following operations.

* Calculate the total global sales for all games in the dataset.
* Find the game with the highest global sales.
* Determine the average sales for each region (NA_Sales, EU_Sales, JP_Sales, Other_Sales).
* Find the top 5 most popular game genres based on global sales.
* Calculate the total sales for each genre in each region and find the most popular genre in North America (NA_Sales).
* Display last 10 rows.
* Determine the top 3 gaming platforms with the highest global sales.
* Calculate the market share (percentage of global sales) for each genre.
* Calculate the correlation coefficient between NA_Sales and EU_Sales. (.corr function)

In [96]:
import pandas as pd
data = pd.read_csv("https://raw.githubusercontent.com/TirendazAcademy/PANDAS-TUTORIAL/main/DataSets/vgsalesGlobale.csv")
data

Rank                                              Name Platform  \
0          1                                        Wii Sports      Wii   
1          2                                 Super Mario Bros.      NES   
2          3                                    Mario Kart Wii      Wii   
3          4                                 Wii Sports Resort      Wii   
4          5                          Pokemon Red/Pokemon Blue       GB   
...      ...                                               ...      ...   
16593  16596                Woody Woodpecker in Crazy Castle 5      GBA   
16594  16597                     Men in Black II: Alien Escape       GC   
16595  16598  SCORE International Baja 1000: The Official Game      PS2   
16596  16599                                        Know How 2       DS   
16597  16600                                  Spirits & Spells      GBA   

         Year         Genre   Publisher  NA_Sales  EU_Sales  JP_Sales  \
0      2006.0        Sports    Nintendo     41.49     29.02      3.77   
1      1985.0      Platform    Nintendo     29.08      3.58      6.81   
2      2008.0        Racing    Nintendo     15.85     12.88      3.79   
3      2009.0        Sports    Nintendo     15.75     11.01      3.28   
4      1996.0  Role-Playing    Nintendo     11.27      8.89     10.22   
...       ...           ...         ...       ...       ...       ...   
16593  2002.0      Platform       Kemco      0.01      0.00      0.00   
16594  2003.0       Shooter  Infogrames      0.01      0.00      0.00   
16595  2008.0        Racing  Activision      0.00      0.00      0.00   
16596  2010.0        Puzzle    7G//AMES      0.00      0.01      0.00   
16597  2003.0      Platform     Wanadoo      0.01      0.00      0.00   

       Other_Sales  Global_Sales  
0             8.46         82.74  
1             0.77         40.24  
2             3.31         35.82  
3             2.96         33.00  
4             1.00         31.37  
...            ...           ...  
16593         0.00          0.01  
16594         0.00          0.01  
16595         0.00          0.01  
16596         0.00          0.01  
16597         0.00          0.01  

[16598 rows x 11 columns]

In [97]:
global_sales = data["Global_Sales"].sum()
print("The total global sales are : ",global_sales)

The total global sales are :  8920.44


In [101]:
highest_global = data["Global_Sales"].max()
h = data[data["Global_Sales"] == highest_global]
h["Name"]

0    Wii Sports
Name: Name, dtype: object

In [104]:
print("Average sales for NA Region : ",data["NA_Sales"].mean())
print("Average sales for EU Region : ",data["EU_Sales"].mean())
print("Average sales for JP Region : ",data["JP_Sales"].mean())
print("Average sales for Other Region : ",data["Other_Sales"].mean())

Average sales for NA Region :  0.26466742981082064
Average sales for EU Region :  0.14665200626581515
Average sales for JP Region :  0.077781660441017
Average sales for Other Region :  0.0480630196409206


In [106]:
data.sort_values(by="Global_Sales", ascending = False, inplace=True)
print(data["Genre"].head(5))

0          Sports
1        Platform
2          Racing
3          Sports
4    Role-Playing
Name: Genre, dtype: object


In [136]:
genre = data["Genre"].unique()
north_america_genres = {}
for g in genre:
    genre_group = data[data["Genre"] == g]
    print("Sum of NA_region of ",g," is ",genre_group["NA_Sales"].sum())
    north_america_genres[g] = genre_group["NA_Sales"].sum()
    print("Sum of EU_region of ",g," is ",genre_group["EU_Sales"].sum())
    print("Sum of JP_region of ",g," is ",genre_group["JP_Sales"].sum())

Sum of NA_region of  Sports  is  683.35
Sum of EU_region of  Sports  is  376.85
Sum of JP_region of  Sports  is  135.37
Sum of NA_region of  Platform  is  447.05
Sum of EU_region of  Platform  is  201.63000000000002
Sum of JP_region of  Platform  is  130.77
Sum of NA_region of  Racing  is  359.41999999999996
Sum of EU_region of  Racing  is  238.39000000000001
Sum of JP_region of  Racing  is  56.69
Sum of NA_region of  Role-Playing  is  327.28
Sum of EU_region of  Role-Playing  is  188.05999999999997
Sum of JP_region of  Role-Playing  is  352.31
Sum of NA_region of  Puzzle  is  123.78
Sum of EU_region of  Puzzle  is  50.779999999999994
Sum of JP_region of  Puzzle  is  57.309999999999995
Sum of NA_region of  Misc  is  410.24
Sum of EU_region of  Misc  is  215.98000000000002
Sum of JP_region of  Misc  is  107.76
Sum of NA_region of  Shooter  is  582.6
Sum of EU_region of  Shooter  is  313.27000000000004
Sum of JP_region of  Shooter  is  38.279999999999994
Sum of NA_region of  Simulation  

In [137]:
values = list(north_america_genres.values())
m = max(values)
for k in north_america_genres.keys():
    if north_america_genres[k] == m:
        print("The most popular genre of north america is ",k)

The most popular genre of north america is  Action


In [108]:
data.tail(10)

Rank                                               Name Platform  \
16588  16591                                   Mega Brain Boost       DS   
16590  16593  Eiyuu Densetsu: Sora no Kiseki Material Collec...      PSP   
16561  16564                                     Kanokon: Esuii      PS2   
16591  16594                                Myst IV: Revelation       PC   
16592  16595                                           Plushees       DS   
16593  16596                 Woody Woodpecker in Crazy Castle 5      GBA   
16594  16597                      Men in Black II: Alien Escape       GC   
16595  16598   SCORE International Baja 1000: The Official Game      PS2   
16596  16599                                         Know How 2       DS   
16597  16600                                   Spirits & Spells      GBA   

         Year         Genre              Publisher  NA_Sales  EU_Sales  \
16588  2008.0        Puzzle  Majesco Entertainment      0.01      0.00   
16590  2007.0  Role-Playing     Falcom Corporation      0.00      0.00   
16561  2008.0     Adventure                    5pb      0.00      0.00   
16591  2004.0     Adventure                Ubisoft      0.01      0.00   
16592  2008.0    Simulation              Destineer      0.01      0.00   
16593  2002.0      Platform                  Kemco      0.01      0.00   
16594  2003.0       Shooter             Infogrames      0.01      0.00   
16595  2008.0        Racing             Activision      0.00      0.00   
16596  2010.0        Puzzle               7G//AMES      0.00      0.01   
16597  2003.0      Platform                Wanadoo      0.01      0.00   

       JP_Sales  Other_Sales  Global_Sales  
16588      0.00          0.0          0.01  
16590      0.01          0.0          0.01  
16561      0.01          0.0          0.01  
16591      0.00          0.0          0.01  
16592      0.00          0.0          0.01  
16593      0.00          0.0          0.01  
16594      0.00          0.0          0.01  
16595      0.00          0.0          0.01  
16596      0.00          0.0          0.01  
16597      0.00          0.0          0.01

In [109]:
print(data["Platform"].head(3))

0    Wii
1    NES
2    Wii
Name: Platform, dtype: object


In [139]:
total = data["Global_Sales"].sum()
genre = data["Genre"].unique()
for g in genre:
    genre_group = data[data["Genre"] == g]
    s = genre_group["Global_Sales"].sum()
    print("Market share of ", g, " is : ", s/total)

Market share of  Sports  is :  0.14920003945993696
Market share of  Platform  is :  0.09319831757177896
Market share of  Racing  is :  0.08206321661263345
Market share of  Role-Playing  is :  0.10396011855917421
Market share of  Puzzle  is :  0.027459407831900665
Market share of  Misc  is :  0.0907982117474026
Market share of  Shooter  is :  0.11629134885723126
Market share of  Simulation  is :  0.04396644111725431
Market share of  Action  is :  0.1963109443031958
Market share of  Fighting  is :  0.05032375084637081
Market share of  Adventure  is :  0.026796884458614143
Market share of  Strategy  is :  0.01963131863450682


In [144]:
print("The correlation coefficient : ",data["NA_Sales"].corr(data["EU_Sales"]))

The correlation coefficient :  0.7677267483702634
